apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: postgresqldb
          image: postgres:14.1
          resources:
            # Add resource requirements here
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: petclinic
            - name: POSTGRES_USER
              value: petclinic
            - name: POSTGRES_DB
              value: petclinic
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - petclinic
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-db-service
spec:
  selector:
    app: petclinic
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
